# Generated by Django 4.2.3 on 2024-08-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('number', models.IntegerField(blank=True, default=0, verbose_name='Número')),
                ('zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('neighborhood', models.CharField(blank=True, max_length=255, verbose_name='Bairro')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
