# Generated by Django 4.2.3 on 2024-07-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua'),
        ),
    ]
