# Generated by Django 4.2.3 on 2024-07-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_neighborhood_customer_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ'),
        ),
    ]
