# Generated by Django 4.2.3 on 2024-08-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('contact', models.CharField(max_length=255, verbose_name='Contato')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['cidade'],
            },
        ),
    ]
