# Generated by Django 4.2.3 on 2024-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.CharField(default='Jair de Souza', max_length=255, verbose_name='Responsável (Nome que será apresentado no orçamento)'),
            preserve_default=False,
        ),
    ]
