# Generated by Django 4.2.3 on 2024-08-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Valor mensalidade')),
                ('maximum_installments', models.PositiveIntegerField(blank=True, default=1, verbose_name='Número máximo de parcelas')),
                ('cash_discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Desconto à vista (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de emissão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('leased_equipment', models.BooleanField(verbose_name='Equipamento alugado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Orçamento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do orçamento',
                'verbose_name_plural': 'Itens do orçamento',
            },
        ),
    ]
