# Generated by Django 4.2.3 on 2024-07-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='leased_equipment',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='leased_equipment',
            field=models.BooleanField(default=False, verbose_name='Equipamento alugado'),
            preserve_default=False,
        ),
    ]
