# Generated by Django 4.2.3 on 2024-07-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_leased_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Desconto à vista (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='down_payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=5, verbose_name='Entrada (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='maximum_installments',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Número máximo de parcelas'),
        ),
    ]
