# Generated by Django 4.2.3 on 2024-07-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cash_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Valor mensalidade'),
        ),
    ]
